### ISSUE TITLE
More info should be displayed in Order Detail page

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#103]
The current order detail page according to XD is:
![Screenshot 2019-12-30 at 1 15 08 PM](https://user-images.githubusercontent.com/1173819/71567968-96eaf480-2b06-11ea-9137-3d0fdadfc157.png)

But, the current mail Mika recieves once an order is placed is like:
新規受注のお知らせ
オンラインストアにて新規受注が入りました。

注文番号 #10060

注文を表示
注文情報

注文番号 #: 10060
注文日: 2019年10月16日
合計: ¥5,000
支払状況: 支払済み 
決済方法: Stripe
請求情報

Sato Yukiko 様
日本, 〒158-0083 
東京都世田谷区奥沢2-46-13	
0339980314
sakimoto-y@ezweb.ne.jp	
お届け先

Sato Yukiko 様
日本 〒158-0083 
東京都世田谷区奥沢2-46-13	
0339980314

配送方法: 通常配送 (3~5日程度) 

注文内容

商品	数量	合計
ネパールストール大判（生地ミックス）
色: 薄グレー 
価格: ¥5,000	1	¥5,000
小計	¥5,000
配送料	¥0
消費税	¥0
合計	¥5,000
Wix ストア お客様アンケート
今後のサービス向上のため、レビューにご協力ください
レビューを追加

So I think we need to display all of this data in the order detail page. Please let me know your thoughts!

**Comment by ghost** [comment]
<Admin>
注文方法

<Customer>
住所と連絡先

**Comment by dragonfly91** [comment]
@Paglinawan I think we need more detailed design. Please let me know what you think!

**Comment by ghost** [comment]
![ 2020-02-11 17 37 57](https://user-images.githubusercontent.com/32391651/74221526-ab213480-4cf5-11ea-8933-2482dbb5d2a3.jpg)
![ 2020-02-11 17 40 33](https://user-images.githubusercontent.com/32391651/74221534-ad838e80-4cf5-11ea-8dbb-37d675b1ab96.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan お返事ありがとうございます。しかし、すこし勘違いがあると思います。このissueはアドミンがわで見える注文のディテールについてです。今のところだと美香さんにお客様の情報がある長いメールが届きます。でも、アプリではそれはまだ見えないです。簡単にまとめると、この下にあるすべてのテキストをアプリでアドミンの注文ディテールページで見せる必要があります。そのためのデザインお願いします。もし必要であれば、電話で確認することが可能なので、教えてください。

**Comment by ghost** [comment]
![ 2020-02-15 9 14 53](https://user-images.githubusercontent.com/32391651/74577688-cfba2c80-4fd3-11ea-91a8-628804192107.jpg)
![ 2020-02-15 9 15 06](https://user-images.githubusercontent.com/32391651/74577692-d9439480-4fd3-11ea-99a8-9a1f55b2f7e4.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan thank you. Can you please update the XD design doc as well?
