### ISSUE TITLE
Need option to delete stock

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#104]
Currently, only addition is supported. Need to support deletion too. 
![Screenshot 2019-12-30 at 2 48 38 PM](https://user-images.githubusercontent.com/1173819/71569587-81c89280-2b13-11ea-85c2-0ec9bb67880b.png)

**Comment by ghost** [comment]
![ 2020-01-12 14 47 14](https://user-images.githubusercontent.com/32391651/72214700-a4fb3500-354a-11ea-9e4b-4ebd88394d3f.jpg)

**Comment by ghost** [comment]
![ 2020-01-12 14 47 23](https://user-images.githubusercontent.com/32391651/72214742-4bdfd100-354b-11ea-89a6-81ccf618c9ac.jpg)
