### ISSUE TITLE
Add Stock Redesign

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#105]
Due to some technical limitations, the original XD design could not be implemented. The original XD design was: 
![Screenshot 2019-12-30 at 8 21 46 PM](https://user-images.githubusercontent.com/1173819/71579948-06320a00-2b42-11ea-9fe3-9db929b6b657.png)

I revamped the design to look like this: 
![Screenshot 2019-12-30 at 8 19 49 PM](https://user-images.githubusercontent.com/1173819/71579894-e00c6a00-2b41-11ea-987f-b0b5b6012b4c.png)

In essence, instead of opening a dialog, the plus button would now open a new page. So, a minimal redesign of the "Add Stock" page would be really helpful. Please let me know your thoughts!

**Comment by ghost** [comment]
OK

**Comment by dragonfly91** [comment]
@Paglinawan can you please confirm if the design proposed by me is okay?

**Comment by ghost** [comment]
@dragonfly91 I confirmed. It's okey^^
