### ISSUE TITLE
Size and color info in product detail might be misleading

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#106]
Can you please explain what is the meaning of the Sizes and Colors here (in admin product detail page)? 

![Screenshot 2020-01-01 at 10 35 10 AM](https://user-images.githubusercontent.com/1173819/71637313-0554c180-2c83-11ea-947c-6348b8be3004.png)

For example, let's consider this case:

T Shirts
White + L : 5
Brown + S : 5

Should I display:
Color: W, Br
Size: L, S

But, White + S = 0 and Brown + L = 0. We don't have stock for these combinations. 

So, if I display the size and color as a list, it might be misleading. Should we display the tiles here instead, along with the stock (quantity) info? Please let me know your thoughts!

**Comment by ghost** [comment]
![ 2020-01-12 14 40 00](https://user-images.githubusercontent.com/32391651/72214625-716bdb00-3549-11ea-8653-23ab3ea18aac.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan updated the design doc.
