### ISSUE TITLE
Customer product detail color and size design suggestions

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#109]
![Screenshot 2020-01-02 at 1 11 55 PM](https://user-images.githubusercontent.com/1173819/71651511-7a96c400-2d61-11ea-832d-45829e8cfd82.png)

- Why do we need to support the + button in the customer product detail view? If the customer wants to order two colors, can't they do "add to cart" twice? If we follow the 80%-20% rule, we have to make the application easy to use for 80% of the use cases. I think it's very rare that customers would like to place orders with different color and size combinations in the same order.  So I think we can simplify this design further. Compared with Amazon's design:
![IMG_3113](https://user-images.githubusercontent.com/1173819/71651598-4079f200-2d62-11ea-874d-70bf5f72c6c4.PNG)

- Also, since the buttons are right next to each other, it's easy to tap the wrong button by mistake, especially when trying to tap on the "-" button. Maybe, the padding around the buttons can be increased.

Please let me know your thoughts!

**Comment by dragonfly91** [comment]
Amazon follow

**Comment by ghost** [comment]
![ 2020-01-12 14 37 00](https://user-images.githubusercontent.com/32391651/72214600-09b59000-3549-11ea-9033-2a33a2d8540a.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan can you please update the XD design doc?

**Comment by ghost** [comment]
![ 2020-02-11 17 23 11](https://user-images.githubusercontent.com/32391651/74220533-36e59180-4cf3-11ea-81e8-7ad0370d4182.jpg)

**Comment by dragonfly91** [comment]
Need to distinguish these types of stock values: SizeAndColor, SizeOnly, ColorOnly.
