### ISSUE TITLE
Need to distinguish between Stock Types

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#116]
I think we need to have these types of stock: SizeAndColor, SizeOnly, ColorOnly. We need to provide a way for admin to set the right type of stock when creating a new product. 

For example:
T Shirt : SizeAndColor
Coffee Beans : SizeOnly
Cross Ear Ring Accessory : ColorOnly

Can we add an extra dropdown menu in the Add New Product page? If yes, need the corresponding Japanese text.

Note: once a product is created with a certain stock type, it cannot be changed later.

**Comment by ghost** [comment]
![ 2020-02-20 11 50 19](https://user-images.githubusercontent.com/32391651/74896260-31650700-53d7-11ea-93e8-f711e1b9beb4.jpg)

**Comment by ghost** [comment]
サイズのみ選択
サイズと色を選択
色のみ選択
