### ISSUE TITLE
Push notification when new order placed

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#118]
Need design (text and other content) for push notification when a new order is placed. Maybe something like this:
![image](https://user-images.githubusercontent.com/1173819/74734308-9dd5ee00-5291-11ea-892e-b132bf903105.png)

**Comment by dragonfly91** [comment]
When order placed -> To admin
When new product published -> To customer
When order completed -> To customer

**Comment by ghost** [comment]
When order placed -> To admin
**発注のお知らせ**
[name] 様より[product]、他[total]品の注文が入りました

**Comment by ghost** [comment]
When new product published -> To customer
**新製品のお知らせ**
[product]が新入荷(^^)/ 詳しくはコチラから♪

**Comment by ghost** [comment]
When order completed -> To customer
**注文完了のお知らせ**
ただ今注文を承りました。発送までしばらくお待ちください。

**Comment by dragonfly91** [comment]
Thank you!

**Comment by dragonfly91** [comment]
need Apple developer account (payment required). blocking this for now.

**Comment by dragonfly91** [comment]
Got apple developer account

**Comment by dragonfly91** [comment]
Need to follow this guide: https://fireship.io/lessons/flutter-push-notifications-fcm-guide/
