### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#119]
When user taps on the Settings button in the drawer:

<img width="456" alt="Screen Shot 2020-02-18 at 21 25 41" src="https://user-images.githubusercontent.com/1173819/74736158-797c1080-5295-11ea-8ed4-85acac451ac7.png">

need to open the settings page:

<img width="436" alt="Screen Shot 2020-02-18 at 21 26 07" src="https://user-images.githubusercontent.com/1173819/74736194-8993f000-5295-11ea-9ea5-57d5dbf4a19f.png">

which currently contains a toggle switch for enable / disable show tax next to price. When user changes the state, this must be saved in the User record in database (setting `currentSignedInUser.setting.showTax` to `True` or `False`)

The design is available in BadiUp-Admin.xd file in GoogleDrive. All the text should be copy-pasted from the design file. When unsure about meaning of certain Japanese words / phrases, please check Google Translate or post in slack where someone can help.

**Comment by DavidCuentasMar** [comment]
What does admin-user means? Only admin can access this view or both (admin and user) ?

**Comment by dragonfly91** [comment]
@DavidCuentasMar Sorry, there was a mistake in the issue description - this issue is for enabling / disabling whether the price is tax inclusive or not. So, I gave some comments accordingly.
