### ISSUE TITLE
Need Japanese text for confirm exit dialog

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#12]
dialog shown when pressing back button. In admin new product page

![Screenshot 2019-11-22 at 8 28 25 PM](https://user-images.githubusercontent.com/1173819/69422306-af792980-0d66-11ea-9f5b-da6ca75dfcdc.png)

**Comment by ghost** [comment]
変更内容を保存しますか？
--
変更内容を保存して、
後で編集を続けられるようにしますか
--
キャンセル   |　保存

**Comment by dragonfly91** [comment]
Thank you @Paglinawan ! Closing this issue now.
