### ISSUE TITLE
Customer shouldn’t be able to order more than available stock

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#125]
When current product stock is less than the quantity customer is trying to buy, this should be prevented and a message should be displayed. Maybe something like `Only 2 items available. Please order soon!`

**Comment by dragonfly91** [comment]
This would mean two items:

1. Quantity selector should have a max limit 
- this could be equal to the current available stock quantity of the given product or
- this could be set as a constant (for example 10 items)
2. When quantity is less than a threshold value, a message should be displayed in the product detail page - this could be shown as a row in the page itself and not as a dialog. Something like this:
![image](https://user-images.githubusercontent.com/1173819/75198097-ce33f580-5785-11ea-85e6-8b9fa0b65123.png)
 
3. The message could be something like `only x items remaining` or `only a few items remaining`
4. The threshold value can be set by admin per product or could be a global default value (for example 10 items)

**Comment by dragonfly91** [comment]
@Paglinawan please let me know what you think!

**Comment by ghost** [comment]
![ 2020-03-11 17 44 06](https://user-images.githubusercontent.com/32391651/76398285-f6476980-63bf-11ea-88d4-16c14c125115.jpg)
![ 2020-03-11 17 44 17](https://user-images.githubusercontent.com/32391651/76398288-f7789680-63bf-11ea-9982-4fe91ca3c0de.jpg)

**Comment by dragonfly91** [comment]
Closing design ticket. Created https://github.com/GospelAid/badiup/issues/168 to track this.
