### ISSUE TITLE
Customers should be allowed to input shipping address and phone number when buying things.

### ISSUE THREAD

**Issue by charleshenryhugo** [GospelAid/badiup#130]
Customers should be allowed to input shipping address and phone number when buying things.
Therefore the interface needs to be designed.
お客が買い物するとき、お届け先と電話番号を入力すべきだと考えています。この機能をデザインしていただきたいです。

The current interface allows customers to input the shipping method and paying method.
今のデザインだと、お客さんが支払い方法と配送方法しか編集できない。
![image](https://user-images.githubusercontent.com/7455400/75090076-a173b880-55a2-11ea-8160-957a8765f238.png)

**Comment by ghost** [comment]
![ 2020-02-23 13 46 29](https://user-images.githubusercontent.com/32391651/75103771-fff07380-5642-11ea-8e59-ea61aa1d002b.jpg)
Googleアカウントから自動で取得できれば、より良いです

**Comment by dragonfly91** [comment]
@Paglinawan ありがとうございます！XDをもアップしましたか？

**Comment by charleshenryhugo** [comment]
ありがとうございます！

**Comment by dragonfly91** [comment]
I see that the XD doc has been updated. Reassigning this PR to @charleshenryhugo for now
