### ISSUE TITLE
Cart action buttons might be confusing

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#134]
Currently we support "Add to Cart" and "Go to Cart" buttons in product detail page in customer view. When customer taps on the "Add to Cart" button, the selected product is added to the Cart and a snack bar is shown. When the customer taps on the "Go to Cart" button, the selected product is added to cart and then the app navigates to the cart page. These two behaviors are well meant in their own right on their own. However, if a user decides to add first and then go to cart, then the product will be added to the cart twice. To fix this, we can consider removing the "Go to Cart" button and instead, ask the customer to tap on the Cart icon in the snack bar message. 

<img width="454" alt="Screen Shot 2020-02-22 at 18 10 13" src="https://user-images.githubusercontent.com/1173819/75121836-4beef700-56db-11ea-80b4-839c3ac8189c.png">

**Comment by ghost** [comment]
![ 2020-03-11 17 38 26](https://user-images.githubusercontent.com/32391651/76397822-22aeb600-63bf-11ea-9dc9-341336a8f498.jpg)

**Comment by ghost** [comment]
![ 2020-03-11 19 53 09](https://user-images.githubusercontent.com/32391651/76409820-462f2c00-63d2-11ea-9ee4-ef9c8bdaf9dd.jpg)
