### ISSUE TITLE
Quantity decrease button should be inactive when value is at minimum

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#135]
The minimum value possible for the quantity selector everywhere is 1. Since the user can’t reduce this less than 1, once the value reaches 1, the "minus" button should appear inactive. Ideas welcome!
<img width="448" alt="Screen Shot 2020-02-24 at 9 22 36" src="https://user-images.githubusercontent.com/1173819/75123063-6d55e000-56e7-11ea-8d76-4866cb4c81de.png">

**Comment by ghost** [comment]
I see!
it should change the color and disable
![ 2020-02-24 16 30 11](https://user-images.githubusercontent.com/32391651/75134974-56cd7a00-5723-11ea-8757-41038d4e0820.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan can you please update the XD file as well?

**Comment by dragonfly91** [comment]
Closing this design ticket and tracking this work item with https://github.com/GospelAid/badiup/issues/163
