### ISSUE TITLE
Add "About Badi" and "Privacy Policy" to Main Menu

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#140]
Need design to add links to the "About Badi" and "Privacy Policy" pages in the main menu.

<img width="452" alt="Screen Shot 2020-03-01 at 22 10 30" src="https://user-images.githubusercontent.com/1173819/75629359-82f86780-5c09-11ea-9b8c-bf0c8e044c9e.png">

**Comment by ghost** [comment]
![ 2020-03-16 14 28 18](https://user-images.githubusercontent.com/32391651/76725723-72f89000-6792-11ea-907e-685d99eacce8.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan I think we need a link to Privacy Policy as well. What do you think?

**Comment by ghost** [comment]
![ 2020-03-16 22 09 16](https://user-images.githubusercontent.com/32391651/76761500-de625200-67d2-11ea-8b06-d8cb65e1dd1a.jpg)
