### ISSUE TITLE
Support QuantityOnly stock type

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#143]
Currently, we support these stock types:
1. Size and Color
2. Size only
3. Color only

After discussion with Mika, I think we need to have a 4th stock type:
4. Quantity only

This is especially useful for items that don’t have either size or color attributes, like coffee beans etc. 

@Paglinawan need the design (including related Japanese texts) for this new stock type.

**Comment by ghost** [comment]
![ 2020-03-11 17 33 07](https://user-images.githubusercontent.com/32391651/76397463-7371df00-63be-11ea-9d7e-8632c32e0a2e.jpg)
![ 2020-03-11 17 33 17](https://user-images.githubusercontent.com/32391651/76397467-753ba280-63be-11ea-8999-f8e221d31ee2.jpg)

**Comment by dragonfly91** [comment]
When 4. number only is selected, a text input field should be displayed instead of the grid.

**Comment by dragonfly91** [comment]
@Paglinawan when カテゴリータイプ＝在庫数のみを選択, how should this be displayed in the product detail page (admin and customer)? Currently, it is displayed like this:

<img width="458" alt="Screen Shot 2020-03-16 at 22 23 36" src="https://user-images.githubusercontent.com/1173819/76808736-00d48980-682c-11ea-9fe7-1880f55af1c0.png">

**Comment by ghost** [comment]
![ 2020-03-17 15 30 37](https://user-images.githubusercontent.com/32391651/76828628-c3d8b900-6864-11ea-84fb-dff2619cfa6f.jpg)
