### ISSUE TITLE
Ability to add new colors and sizes

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#144]
Need ability to add new colors and sizes and manage existing ones. 

Can be a functionality in the Settings page in admin view. 

Should be able to pick the color from a color chart. 
Should be able to set the display text that should be visible against a particular color.

**Comment by dragonfly91** [comment]
We can implement this color palette: https://pub.dev/packages/flutter_colorpicker#-readme-tab-

**Comment by ghost** [comment]
![ 2020-03-10 10 44 39](https://user-images.githubusercontent.com/32391651/76271563-3fae9080-62bc-11ea-8ebc-531227fdaf90.jpg)

**Comment by dragonfly91** [comment]
Closing this design ticket and created this engineering ticket to track this work item: https://github.com/GospelAid/badiup/issues/162
