### ISSUE TITLE
Add Contact Us

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#147]
Need to add a way to contact us for dealing with issues - maybe LINE message.

**Comment by ghost** [comment]
![ 2020-03-09 14 19 44](https://user-images.githubusercontent.com/32391651/76184924-0ec55180-6211-11ea-991b-94cfbc05b482.jpg)
![ 2020-03-09 10 01 14](https://user-images.githubusercontent.com/32391651/76184935-1258d880-6211-11ea-8973-a2a2310b25e4.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan please update the XD file
