### ISSUE TITLE
Need "My Orders" page in Customer main menu

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#151]
I think we need to provide "My Orders" page in Customer view - in main menu which opens a page, where the customer can check the status of their orders. Please let me know what you think! @Paglinawan

**Comment by ghost** [comment]
![ 2020-03-09 10 14 35](https://user-images.githubusercontent.com/32391651/76175221-d6ad1700-61ee-11ea-8dba-e042a622ebd6.jpg)
![ 2020-03-09 10 14 48](https://user-images.githubusercontent.com/32391651/76175224-da409e00-61ee-11ea-9427-0c80d63fe5bf.jpg)

**Comment by ghost** [comment]
![ 2020-03-09 9 57 59](https://user-images.githubusercontent.com/32391651/76175241-ed536e00-61ee-11ea-9a71-17d49263a8bd.jpg)
![ 2020-03-09 10 01 14](https://user-images.githubusercontent.com/32391651/76175243-f04e5e80-61ee-11ea-8a10-d0d69a6214d1.jpg)

**Comment by dragonfly91** [comment]
Thank you. Can you please update XD as well? @Paglinawan

**Comment by dragonfly91** [comment]
Closing the design issue. Created https://github.com/GospelAid/badiup/issues/161 to track the engineering work for this.
