### ISSUE TITLE
Card button design

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#152]
Currently implemented card button looks like this:

<img width="454" alt="Screen Shot 2020-03-05 at 16 50 02" src="https://user-images.githubusercontent.com/1173819/75970426-a70ebe00-5f13-11ea-95f6-6d8e255151b2.png">

@Paglinawan It looks like we can design the "Add Card" button as per our liking. Can you please create the design for the button (including the layout etc)?

**Comment by ghost** [comment]
タイトル「お支払情報」追加
余白
カード→カード情報
