### ISSUE TITLE
Need to be able to add tracking URL in order detail

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#154]
Admin should be able to add tracking URL in order detail. This should be a necessary condition that needs to be met before the order can be marked as dispatched.

**Comment by ghost** [comment]
![ 2020-03-09 9 54 30](https://user-images.githubusercontent.com/32391651/76174663-158d9d80-61ec-11ea-9c57-eb12dfdd8a7a.jpg)
![ 2020-03-09 9 54 40](https://user-images.githubusercontent.com/32391651/76174669-19b9bb00-61ec-11ea-9947-4aaafef49b9f.jpg)

**Comment by ghost** [comment]
![ 2020-03-09 10 19 23](https://user-images.githubusercontent.com/32391651/76175343-84b8c100-61ef-11ea-8106-f0ca2b9b1ec6.jpg)

**Comment by dragonfly91** [comment]
Thanks! I just had a talk with Mika and looks like we currently use two delivery services:
1. Japan Post
2. Yamato

I think we also need to tell the customer which service it is along with the tracking number. Can you incorporate these as well into the design?

**Comment by ghost** [comment]
![ 2020-03-10 9 33 29](https://user-images.githubusercontent.com/32391651/76268750-7089c800-62b2-11ea-83b4-6a396075253b.jpg)
![ 2020-03-10 9 33 55](https://user-images.githubusercontent.com/32391651/76268754-7384b880-62b2-11ea-953b-52032b19cdff.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan  I think the delivery service selection should be a dropdown menu or a radio button. A checkbox indicates that both the services can be selected, but this is not the case. Can you please update the design?

**Comment by ghost** [comment]
![ 2020-03-11 17 23 23](https://user-images.githubusercontent.com/32391651/76396743-1c1f3f00-63bd-11ea-8f10-424c0442f38e.jpg)

**Comment by dragonfly91** [comment]
Closing the design ticket and tracking this work item with https://github.com/GospelAid/badiup/issues/166
