### ISSUE TITLE
Update the list of colors and sizes according to spreadsheet

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#176]
Get the list of sizes and colors specified in the spreadsheet and update the respective enums in code.

**Comment by ghost** [comment]
please check the following
https://docs.google.com/spreadsheets/d/1WdUM_upvBdUBWFsdd7E3Rcbs_HcEf-qlQae8SBZMUoU/edit#gid=0

**Comment by dragonfly91** [comment]
@Paglinawan thanks for updating the spreadsheet. I found the necessary info. 

<img width="427" alt="Screen Shot 2020-03-20 at 15 05 13" src="https://user-images.githubusercontent.com/1173819/77140224-4c04cb80-6abc-11ea-9e87-3b65d932b12f.png">

**Comment by kumilange** [comment]
@dragonfly91
I assume the enums defined in `stock_model.dart` need to be updated for this issue but I need to confirm some info about `Size`, `ItemColor` and `TextColor`. Could you provide the info below with bold style?

---
**Size:**
n => ""
S => small
M => medium
L => large
XS => **xtraSmall?**
2L => **doubleLarge?**
3L => **tripleLarge?**

---
**ItemColor:**
n => transparent
W => kPaletteWhite
Bl => paletteBlackColor
P => **?**
G => **?**
Br => paletteBrownColor

---
**TextColor:**
n => paletteGreyColor2
W => paletteGreyColor2
Bl => kPaletteWhite
P => **?**
G => **?**
Br => kPaletteWhite

**Comment by dragonfly91** [comment]
@kumiko-haraguchi very good find! 
I think these are variable names, so feel free to name them! I personally prefer:

```
XS => extraSmall
2L => large2
3L => large3
```

I started a thread with @Paglinawan regarding the values for the colors.
