### ISSUE TITLE
Filters - remove prefixes

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#178]
The highlighted portion in red is not required! This should be done for all the filters throughout the app.

<img width="456" alt="Screen Shot 2020-03-20 at 10 04 42" src="https://user-images.githubusercontent.com/1173819/77128102-472b2200-6a92-11ea-9f52-f687a86fda09.png">

**Comment by DavidCuentasMar** [comment]
Like this?

![Screenshot_20200320_001513_com gospelaid badiup](https://user-images.githubusercontent.com/5695447/77138454-1f12d300-6a40-11ea-84a4-25d7741faf2f.jpg)

**Comment by dragonfly91** [comment]
Yes, that looks good to me. @Paglinawan can you please check if this is easy to understand for the customers? I think it will be better to add a label on top of the drop down menu.

**Comment by dragonfly91** [comment]
@DavidCuentasMar if you’re planning on working on this issue, can you please assign this to yourself?

**Comment by DavidCuentasMar** [comment]
@Paglinawan Any updates on this?

**Comment by ghost** [comment]
そのアイディアを採用します
プレースホルダにラベル（サイズ／色）を入れてください

**Comment by dragonfly91** [comment]
@DavidCuentasMar the design suggested by you is good! You can the hint property (https://api.flutter.dev/flutter/material/DropdownButton/hint.html) to show a hint value in the dropdown menu:

hint for size: サイズ
hint for color: 色

**Comment by DavidCuentasMar** [comment]
The hint property only is shown when there is not item selected in the DropdownButton. So, Right now this change is wouldn't be visible because when the product details page is rendered the DropdownButton already has a selected item
