### ISSUE TITLE
Billing and Shipping Addresses

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#187]
Current design allows only for the shipping address
<img width="434" alt="Screen Shot 2020-03-24 at 8 54 06" src="https://user-images.githubusercontent.com/1173819/77374058-22de8680-6dad-11ea-83a0-db360a07c32e.png">

Recent feedback from Mika is that we need to support both billing and shipping addresses (including phone numbers). Need to update the XD to enter both addresses.

**Comment by ghost** [comment]
![ 2020-03-24 9 15 13](https://user-images.githubusercontent.com/32391651/77375180-13147180-6db0-11ea-985e-647d7ffdc0ab.jpg)
![ 2020-03-24 9 15 33](https://user-images.githubusercontent.com/32391651/77375192-160f6200-6db0-11ea-8f6d-7c1cb42dd1b8.jpg)
![ 2020-03-24 9 15 43](https://user-images.githubusercontent.com/32391651/77375194-16a7f880-6db0-11ea-808f-3b1553be86a2.jpg)
・設定ページに「アカウント」を追加してください
・注文者情報が完全でない場合、支払い前にその入力を求めてください

**Comment by dragonfly91** [comment]
@Paglinawan I think a better design is:

1. When entering a new address, add "check here to save this address for future use". We can store multiple addresses per each user. 
2. During checkout, the user can choose one address for shipping and one address for billing from the existing list of addresses. 

Please let me know your thoughts!

**Comment by dragonfly91** [comment]
I think this design - which asks the customer to add their details before they can place an order - would not encourage shopping. Can we consider adding this during the first checkout flow or some other way which is less intrusive?

<img width="491" alt="Screen Shot 2020-04-08 at 21 19 59" src="https://user-images.githubusercontent.com/1173819/78783562-cf8c4b00-79de-11ea-9931-062f526b6490.png">

**Comment by ghost** [comment]
Thanks for alot
this following are my thoughts

1. I think no need because then user get confused
2. I agree. plz wait, I prepare the design
3. ok, I think we can solve this issue by only changing the user flow
I think we make the user to add that info after signup
@dragonfly91

**Comment by dragonfly91** [comment]
@Paglinawan  to check with Mika if we do away completely with the customer address. In that case, the user always has to update shipping address. 
> provide abilitiy to "Set as default shipping address" in cart page
> can modify this from account page.

**Comment by dragonfly91** [comment]
check box text: お届け先住所と同じ
customer address title: 注文者情報

**Comment by dragonfly91** [comment]
Created engineering ticket https://github.com/GospelAid/badiup/issues/241
