### ISSUE TITLE
Add "About Delivery Method" text to cart page

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#188]
<img width="335" alt="Screen Shot 2020-03-24 at 9 04 09" src="https://user-images.githubusercontent.com/1173819/77374624-8ddc8d00-6dae-11ea-9dc8-632ac27393ca.png">

**Comment by ghost** [comment]
I'm sorry it's hard to understand
Please chenge the txt to the following
----------
ゆうパックもしくは宅急便にて配送致します。
（一律500円の送料がかかります。5,000円以上のお買い上げで送料が無料になります。）
----------
