### ISSUE TITLE
Should include order placed time as well?

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#189]
In Order Listing page, currently, the order placed date is being displayed. However when there are multiple orders placed on the same day, this can become really confusing. Should we include time as well?

<img width="385" alt="Screen Shot 2020-03-24 at 9 12 27" src="https://user-images.githubusercontent.com/1173819/77375050-be70f680-6daf-11ea-8fc9-4f136b10c052.png">

**Comment by ghost** [comment]
I think it's no need
Because in that case,I check order number

**Comment by dragonfly91** [comment]
Can we take Mika's conclusion as well in this regard? @Paglinawan

**Comment by ghost** [comment]
I confirmed,
She said no need too
the reason is that she presume we will not accept many orders
