### ISSUE TITLE
Placement order is not honored

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#190]
When an `Undispatched` Order is marked `Dispatched`, the item's position changes between the filter views.

<img width="454" alt="Screen Shot 2020-03-24 at 9 17 17" src="https://user-images.githubusercontent.com/1173819/77375356-9930b800-6db0-11ea-88f5-6b12892d343c.png">
<img width="454" alt="Screen Shot 2020-03-24 at 9 17 29" src="https://user-images.githubusercontent.com/1173819/77375361-9e8e0280-6db0-11ea-85df-fd07544c57d2.png">
<img width="454" alt="Screen Shot 2020-03-24 at 9 17 44" src="https://user-images.githubusercontent.com/1173819/77375363-9f269900-6db0-11ea-8797-2713bebf7ac3.png">
<img width="454" alt="Screen Shot 2020-03-24 at 9 18 02" src="https://user-images.githubusercontent.com/1173819/77375364-9fbf2f80-6db0-11ea-92a7-b615affe2d9d.png">
<img width="454" alt="Screen Shot 2020-03-24 at 9 18 22" src="https://user-images.githubusercontent.com/1173819/77375366-a057c600-6db0-11ea-911c-f205b3d76959.png">
<img width="454" alt="Screen Shot 2020-03-24 at 9 18 45" src="https://user-images.githubusercontent.com/1173819/77375368-a057c600-6db0-11ea-9aba-23cf0c4c0f6b.png">

**Comment by charleshenryhugo** [comment]
@dragonfly91 
Does this issue mean that: newly dispatched order should be placed as the first one in the `発送済み` list?
If that's the case, I am thinking about adding a `dispatchedDate` field to the Order model and ordering the `発送済み` list by this `dispatchedDate`.
How do you think about this?

**Comment by dragonfly91** [comment]
I think that's good. Then, by design, all dispatched orders would have this field.

**Comment by dragonfly91** [comment]
@charleshenryhugo if you’re working on this, please assign this issue to yourself!
