### ISSUE TITLE
Need design to support bank transfer (furikomi)

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#193]
Need design in XD for supporting furikomi. Please update all the relevant screens where this option would have an impact.

**Comment by ghost** [comment]
![ 2020-04-08 19 34 56](https://user-images.githubusercontent.com/32391651/78774734-10c92e80-79d0-11ea-9ee7-e8bf910cc315.jpg)

**Comment by dragonfly91** [comment]
I think we have to show some extra information about the details of the bank account where the customer should transfer the money. Can you please incorporate that as well in to the design?

**Comment by dragonfly91** [comment]
商品と請求書を同梱いたします。
記載の振込先に、商品到着後一週間を目処にお振込みください。
（振込み手数料はご負担ください）
