### ISSUE TITLE
[Bug] CustomerProductDetailPage is showing all sizes regardless of corresponding colors

### ISSUE THREAD

**Issue by kumilange** [GospelAid/badiup#202]
`CustomerProductDetailPage` is showing all the sizes as options regardless of its corresponding colors. Therefore, if you click the size that doesn't have the default selected color, it throws an error.

---
**For example:**
XS => Pink
2L => Pink
3L => Grey
Default Selected Color = Pink

If you select **3L** first, it throws an error as **3L** doesn't have **Pink** color as selection.
![](http://g.recordit.co/G6hEdDNvdU.gif)

**Comment by dragonfly91** [comment]
I tried to repro this bug but unsuccessful. I created a product according to the repro steps:

<img width="453" alt="Screen Shot 2020-03-31 at 7 13 00" src="https://user-images.githubusercontent.com/1173819/77967161-87569400-731f-11ea-9fa7-1f32089ea645.png">

And tried to select the colors and sizes based on the repro steps: https://youtu.be/Mn-3XsqlwVM

But was unable to get the error mentioned in the description.

**Comment by kumilange** [comment]
@dragonfly91 It seems like drop-downs for size and color don't have **default selected value** anymore when you first open the screen. It says '**サイズ**' '**色**' as default value. I don't know which PR changed the behavior but it fixed the bug!

**Comment by dragonfly91** [comment]
@kumiko-haraguchi I think the change to remove default selected values was introduced as a part of this PR: https://github.com/GospelAid/badiup/pull/197 Glad that the bug is now fixed! Will close the issue.
