### ISSUE TITLE
Selected indication needed in gallery page

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#21]
Need the design for showing selected images in the gallery page. The current design shows all images unselected. Please update the design with some of the images selected.
![Screenshot 2019-11-24 at 6 04 52 PM](https://user-images.githubusercontent.com/1173819/69492354-3227f300-0ee5-11ea-8347-873085e09361.png)

**Comment by Paglinawan** [comment]
![Uploading  2019-11-25 16.24.36.jpg…]()
#

**Comment by dragonfly91** [comment]
Thank you @Paglinawan for updating the design.
