### ISSUE TITLE
Need logo for the app

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#212]
**Minimum size**: 1024p X 1024p
**File format**: PNG
**For more guidelines**: https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

**Comment by ghost** [comment]
![1024](https://user-images.githubusercontent.com/32391651/79682520-fad42d00-825d-11ea-8ac6-46b2af65e86e.jpg)
You can get data from this drive.
if you use svg data then you can edit by only text edita
https://drive.google.com/drive/u/1/folders/1WpmQgtz0oOYsm64flNWdgYOKxJN4Vf1a

**Comment by dragonfly91** [comment]
Related engineering ticket: https://github.com/GospelAid/badiup/issues/242
