### ISSUE TITLE
Add indication for Published / Unpublished product

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#221]
In the product list page (for admin), it is hard to know which product is published and which is unpublished. Can we add a simple display which shows either PUBLISHED or UNPUBLISHED. Can use GREEN and YELLOW colors for these texts. Any ideas are welcome.

<img width="459" alt="Screen Shot 2020-04-08 at 21 58 43" src="https://user-images.githubusercontent.com/1173819/78786903-745d5700-79e4-11ea-8df3-626ae72a1a83.png">

**Comment by ghost** [comment]
![ 2020-04-19 16 41 56](https://user-images.githubusercontent.com/32391651/79682424-12f77c80-825d-11ea-9f23-37be018dcd3e.jpg)
