### ISSUE TITLE
Add missing functionality for "tax included" setting

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#224]
This button currently does nothing

<img width="458" alt="Screen Shot 2020-04-08 at 22 20 54" src="https://user-images.githubusercontent.com/1173819/78788854-504f4500-79e7-11ea-9461-b6602cb88f7c.png">

**Comment by dragonfly91** [comment]
@musichrist この設定は必要ですか？

**Comment by musichrist** [comment]
必要じゃないね。ページごと削除しておけ
