### ISSUE TITLE
Arrows are not clearly visible

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#37]
Left and Right arrows on images are not clearly visible

![Screenshot 2019-11-29 at 5 45 39 PM](https://user-images.githubusercontent.com/1173819/69856051-1602c800-12d0-11ea-993d-711f88e27c28.png)

**Comment by ghost** [comment]
![ 2019-11-30 13 32 43](https://user-images.githubusercontent.com/32391651/69895574-ed350e00-1375-11ea-8f59-62c62a58b39b.jpg)
ok I changed style 
I will share the data later

**Comment by dragonfly91** [comment]
Got data from @Paglinawan
