### ISSUE TITLE
Gallery images are low quality

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#41]
Currently all gallery images are fetched at the lowest quality. At least after selection, need to fetch them at the highest quality before crop. Need design input as well.

**Comment by ghost** [comment]
>Currently all gallery images are fetched at the lowest quality.

I think it's ok...

>At least after selection~

→to agenda(coz i cannot understand...)

**Comment by dragonfly91** [comment]
Fixed by https://github.com/GospelAid/badiup/pull/36
