### ISSUE TITLE
Add gradient overlay beneath delete image button for better visibility

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#48]
In New / Edit Product Page
![Screenshot 2019-12-01 at 8 05 17 PM](https://user-images.githubusercontent.com/1173819/69913052-5603af80-1476-11ea-9aa9-5ad4ef948813.png)

**Comment by ghost** [comment]
![ 2019-12-09 20 05 23](https://user-images.githubusercontent.com/32391651/70431050-760f2080-1abf-11ea-9af0-15bcf706737b.jpg)
icon .. color:#fff / text-shadow
image ... box-shadow
