### ISSUE TITLE
Pop screen when required items are not entered

### ISSUE THREAD

**Issue by ghost** [GospelAid/badiup#58]
@dragonfly91 
入力されていない項目があります
カテゴリ、値段の項目が入力されていません。編集画面に戻って入力してください。
![ 2019-12-09 20 04 51](https://user-images.githubusercontent.com/32391651/70431336-2da43280-1ac0-11ea-90f0-5a92efe6a743.jpg)

**Comment by dragonfly91** [comment]
@Paglinawan does this text change based on situation? For example, if user didn't enter "name", should the text be something like "name is missing"? Please clarify!

**Comment by ghost** [comment]
Yes!
----
＜カテゴリ、値段＞の項目が入力されていません。編集画面に戻って入力してください。
----
＜カテゴリ、値段＞が変数です
