### ISSUE TITLE
Update cart item design

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#60]
Add delete cart item button
Fix orientation of quantity selector

**Comment by dragonfly91** [comment]
Additional feedback from Mika: the delete button should not be very close to the quantity selector

**Comment by ghost** [comment]
![ 2019-12-19 15 57 14](https://user-images.githubusercontent.com/32391651/71151909-507cd680-2278-11ea-9b28-78650b0f2d76.jpg)
