### ISSUE TITLE
Add indication that price is tax inclusive

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#73]
Feedback from Mika. In admin new product / edit page, need checkbox to indicate whether the price is tax inclusive or not.

**Comment by ghost** [comment]
the price is tax inclusive

**Comment by ghost** [comment]
価格の横に追加→（税込）
font-size:.8em;
#888

**Comment by dragonfly91** [comment]
@Paglinawan once XD file is updated, please notify!

**Comment by dragonfly91** [comment]
XD file updated.
