### ISSUE TITLE
Need to support product stock

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#75]
Feedback from Mika. Admin will set stock and when customer places an order, the stock will be reduced. When the stock becomes zero, the product should be displayed as "sold out" and the customer should not be able to place an order. Need design for all these scenarios.

**Comment by ghost** [comment]
![ 2019-12-19 15 44 21](https://user-images.githubusercontent.com/32391651/71151740-da786f80-2277-11ea-9f5d-d0232ba1b487.jpg)
![ 2019-12-19 15 44 35](https://user-images.githubusercontent.com/32391651/71151743-db110600-2277-11ea-8d77-5a06dea9f0a7.jpg)
Id like to discuss about this another day

**Comment by dragonfly91** [comment]
If we have c colors and s sizes, then we will have a total of c x s combinations. So, we need to be able to select quantities for each of the c x s combinations! So, I think this design won't be able to accomplish this. Ideally admin needs to be able to input the quantity against a particular product code. 

Let's talk about this in the next meeting!

**Comment by dragonfly91** [comment]
Tracked by https://github.com/GospelAid/badiup/issues/88
