### ISSUE TITLE
Add snackbar to show item added to cart

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#78]
Feedback from Mika. Need snackbar to show "item added to cart" in product detail page. Need design and text.

**Comment by ghost** [comment]
![ 2019-12-19 14 38 34](https://user-images.githubusercontent.com/32391651/71147853-6769fb80-226d-11ea-9f56-fc6278bbb3eb.jpg)
txt：商品をかごに追加しました
bg：#000 opacity:70%

**Comment by dragonfly91** [comment]
実はMaterialではこういう感じのSnackBarありますけど、それでいいでしょうか？
https://material.io/develop/ios/components/snackbars/

![image](https://user-images.githubusercontent.com/1173819/71219991-53c0a280-230a-11ea-9751-b413a829a82c.png)

**Comment by ghost** [comment]
OKです

**Comment by dragonfly91** [comment]
@Paglinawan can you please update the design in XD file for the sake of completion?
