### ISSUE TITLE
Add Category, color and sizes

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#80]
Need how many categories are possible, their names and which categories need color and/or size qualifiers. Need the mapping between (Category, Size, Color) -> (Product Code - SKU).

**Comment by ghost** [comment]
▼product list
https://docs.google.com/spreadsheets/d/1hR-RU2lcNuMKYzYp4J-rlfu9zmXwE-UpdmFagx0Y6LY/edit#gid=0

**Comment by dragonfly91** [comment]
Tracked by https://github.com/GospelAid/badiup/issues/88
