### ISSUE TITLE
Add Product Stock Selection

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#88]
For stock selection, we have the current design:
![Screenshot 2019-12-21 at 2 25 53 PM](https://user-images.githubusercontent.com/1173819/71303557-d8401d80-23fd-11ea-8280-ef9f1758d665.png)

Can we do the "add stock" in a separate page to reduce clutter? Also, we can summarize the stock list using tiles. I've tried to put down my idea on paper here. If you find it difficult to understand, we can have discuss this in the next meeting.
![IMG_2975](https://user-images.githubusercontent.com/1173819/71303542-8f886480-23fd-11ea-849a-71864fac2b98.jpg)

**Comment by ghost** [comment]
汎用性がないですか..？
如何でしょうか..？
![ 2019-12-27 12 16 05](https://user-images.githubusercontent.com/32391651/71499183-c6012c00-28a2-11ea-866d-117b5461c0ba.jpg)
