### ISSUE TITLE
Update background image for login page

### ISSUE THREAD

**Issue by dragonfly91** [GospelAid/badiup#99]
Currently the XD design file contains this image which contains "Login with Google" button. Need an image without the button. 

![Screenshot 2019-12-27 at 12 49 05 PM](https://user-images.githubusercontent.com/1173819/71500223-5f324180-28a7-11ea-9151-3b60ff499e07.png)

**Comment by ghost** [comment]
![logo](https://user-images.githubusercontent.com/32391651/71538999-77be5c80-2978-11ea-96aa-e9cda22cad4a.png)
![login-bg](https://user-images.githubusercontent.com/32391651/71539000-79882000-2978-11ea-885e-ad9feb12d934.jpg)
